name: Deploy to Vercel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        run: npx vercel --prod --yes --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_DGwsj9N0U5Uajvun605juXv5
          VERCEL_PROJECT_ID: prj_soxHlF3ewprsXPGiFJUjts3OHSOA
